# Generated by Django 4.1 on 2022-11-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_alter_userstodo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstodo',
            name='owner',
            field=models.CharField(max_length=150),
        ),
    ]
